#配置端口号
server:
  port: 8761
#配置数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microservice?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
