#配置数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microservice?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: microservice-eureka-server
#eureka:
 # client:
  #  register-with-eureka: false #表示是否将自己注册到eureka server，默认为true;
   # fetch-registry: false #表示是否从eureka server 获取注册信息，默认为true;
---
spring:
  profiles: peer1 #制定profiles=peer1
server:
  port: 8761 #配置端口号
eureka:
  instance:
    hostname: peer1 #当profiles=peer1时，主机名是peer1
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/ #设置与eureka server交互的地址，查询和注册服务都需要依赖这个地址；多个地址可用逗号分隔。eureka可以不带，
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/ #设置与eureka server交互的地址，查询和注册服务都需要依赖这个地址；多个地址可用逗号分隔。eureka可以不带


# Edit Configurations中按照EurekaServerApplication新增两个Spring Boot
# Program Arguments中分别填写--spring.profiles.active=***
# 其中***为application.yml中的eureka.instance.hostname的值
